// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetWorld.Infrastructure.Persistence;

#nullable disable

namespace PetWorld.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PetWorldDbContext))]
    [Migration("20260207113818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PetWorld.Domain.Entities.ChatHistoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("chat_history", (string)null);
                });

            modelBuilder.Entity("PetWorld.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePln")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Karma dla psów",
                            Description = "Premium karma dla dorosłych psów średnich ras",
                            Name = "Royal Canin Adult Dog 15kg",
                            PricePln = 289m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Karma dla kotów",
                            Description = "Sucha karma dla dorosłych kotów z kurczakiem",
                            Name = "Whiskas Adult Kurczak 7kg",
                            PricePln = 129m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Akwarystyka",
                            Description = "Uzdatniacz wody do akwarium, neutralizuje chlor",
                            Name = "Tetra AquaSafe 500ml",
                            PricePln = 45m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Akcesoria dla kotów",
                            Description = "Wysoki drapak z platformami i domkiem",
                            Name = "Trixie Drapak XL 150cm",
                            PricePln = 399m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Zabawki dla psów",
                            Description = "Wytrzymała zabawka do napełniania smakołykami",
                            Name = "Kong Classic Large",
                            PricePln = 69m
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Gryzonie",
                            Description = "Klatka 60x40cm z wyposażeniem",
                            Name = "Ferplast Klatka dla chomika",
                            PricePln = 189m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Akcesoria dla psów",
                            Description = "Smycz zwijana dla psów do 50kg",
                            Name = "Flexi Smycz automatyczna 8m",
                            PricePln = 119m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "Karma dla kotów",
                            Description = "Karma dla kociąt do 12 miesiąca życia",
                            Name = "Brit Premium Kitten 8kg",
                            PricePln = 159m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Category = "Akwarystyka",
                            Description = "Kompletny zestaw CO2 dla roślin akwariowych",
                            Name = "JBL ProFlora CO2 Set",
                            PricePln = 549m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = "Gryzonie",
                            Description = "Naturalne siano łąkowe, podstawa diety",
                            Name = "Vitapol Siano dla królików 1kg",
                            PricePln = 25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
